name: "tf-validate"
on:
  pull_request:

jobs:
  tf_validate:
    uses: leonmsdev/github-action-templates/.github/workflows/tf-validate.yml@main
    with:
      tf_version: latest                                ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: leonms-landing-zone-rg         ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: leonmslandingzonesa               ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: leonms-landing-zone-tfstate    ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: terraform-fmt                             ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: config-dev.tfvars                   ## Terraform TFVARS (Required)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}               ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}       ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}   ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}               ## ARM Tenant ID
 
      
      